Test add all auth
hatchways/team-scallops pull request #63
Opened 2021-10-20 03:19 UTC by navjot-chahal

### What this PR does:
- Adds mocha tests for `/auth/register`, `/auth/login`, `/auth/user` and `/auth/logout` routes.
- Changes logout request type to "POST" from "GET" for both server and client side.

### Screenshots / Videos:
- CLI mocha test results:
<img width="710" alt="Screen Shot 2021-10-19 at 7 43 45 PM" src="https://user-images.githubusercontent.com/60498899/138020001-32d1e254-d28e-4082-81f1-d52b74e99303.png">

### Any information needed to test this feature:
- Use `npm run dev` to start the test in the server folder.

closes #2

2021-10-20 07:46 UTC, sundayezeilo reviewed
Your tests look good! I Like those screenshots :+1:

2021-10-20 07:46 UTC, ezeilo-su commented on server/test/auth.test.js
> +  // Delete the test user from database
You can remove this comment as the code is clear what is does.

2021-10-20 14:56 UTC, ugur-akin requested changes
Looks great, thanks for you work 👍🏼 I left a  minor comment, take a look and let's check back and merge this soon! 🎉

2021-10-20 14:56 UTC, ugur-akin commented on client/src/helpers/APICalls/logout.ts
> +    method: 'POST',
🙌🏼

2021-10-20 14:56 UTC, ugur-akin commented on server/test/auth.test.js
> +    it("register should return 400 code when user already exists", (pass) => {
`400` is probably not the most appropriate status code for this case (you can find some suggestions on what might be on this [thread](https://stackoverflow.com/questions/9269040/which-http-response-code-for-this-email-is-already-registered/9270432)). 

Ideally, we don't want to define success/failure of our test cases based on the implementation. Therefore I would recommend not looking at the implementation(s) of the feature(s) you're testing as much as possible while designing them (as if to pretend they aren't implemented yet) 👍🏼

2021-10-20 14:56 UTC, ugur-akin commented on server/test/auth.test.js
> +        agent.should.not.have.cookie("token");
❤️

2021-10-21 16:41 UTC, merged

2021-10-21 16:44 UTC, rajivtitus commented
@navjot-chahal why has this branch been merged without approval? :)

2021-10-21 17:52 UTC, navjot-chahal commented
@rajivtitus There was a very minor change. Just the error code response is changed to `409` from `400`. Is there any issue with the last commit?

Also, if this merge was a violation then I will make sure to wait for approval for a minor change as well before merging.

2021-10-21 23:57 UTC, rajivtitus commented
@navjot-chahal There are no issues with the last commit, good work here :)

In the future please wait for approval from a Hatchways team member prior to merging PRs. We review PRs once again to make sure the requested feedback has been implemented or any new issues have been introduced.