Feature add login logout page
hatchways/team-scallops pull request #66
Opened 2021-10-21 00:36 UTC by navjot-chahal

### What this PR does:
- Implement login and signup page according to UI mock.

### Screenshots / Videos:
- Login page Desktop view.

![image](https://user-images.githubusercontent.com/60498899/138190443-dfb7742e-3b41-43c1-a080-0c5dc350dcbf.png)

- Signup page Desktop view.

![image](https://user-images.githubusercontent.com/60498899/138190506-d0242240-089b-49a8-9f70-5c960f670aee.png)

- Login page Mobile view.

![image](https://user-images.githubusercontent.com/60498899/138190587-d0dda9a0-2a1c-4e76-b4f4-95c68664c01b.png)

- Signup page Mobile view.

![image](https://user-images.githubusercontent.com/60498899/138190626-905ffb56-e8d4-4c9e-99ac-fa31856dd97b.png)

### Any information needed to test this feature (required):
- Run `npm start` in the client folder to view the login/signup pages.

closes #26

2021-10-21 10:14 UTC, sundayezeilo reviewed
Good work with this one :+1: 
Best of luck with other tickets!

2021-10-21 12:20 UTC, ugur-akin requested changes
The UI looks very good 🙌🏼 Left a few minor comments for you to address, let's check back and we should be able to merge this soon!

2021-10-21 12:20 UTC, ugur-akin commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +            <Typography className={classes.label}>E-MAIL ADDRESS</Typography>
Reserve the use of capital letters for abbreviations (e.g. `CSS`) for accessibility reasons, instead use CSS to transform the case of a text when necessary. ([ref](https://medium.com/@mandy.michael/why-you-shouldnt-write-your-content-in-uppercase-instead-use-css-b03ac2c65b99))

Ditto throughout 👍🏼

2021-10-21 12:20 UTC, ugur-akin commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +              // endAdornment: <Typography className={classes.forgot}>Forgot?</Typography>,
Let's remove unused/commented code here (or uncomment if it was a temporary change).

2021-10-21 12:20 UTC, ugur-akin commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +            <Typography style={{ fontWeight: 'bold' }}> Don&apos;t have account? </Typography>
Let's avoid using inline styling and move this into the `useStyles` file - inline styles are handy for quickly testing something but ideally they are cleaned up before shipping the code 👍🏼

2021-10-21 12:20 UTC, ugur-akin commented on client/src/pages/Login/LoginForm/useStyles.ts
> +    color: 'rgb(0,0,0)',
Have you tried using `color="textPrimary"` prop on the component for this?

2021-10-21 12:20 UTC, ugur-akin commented on client/src/pages/SignUp/useStyles.ts
> +    fontFamily: theme.typography.fontFamily,
Do we need this?

2021-10-21 17:23 UTC, navjot-chahal commented on client/src/pages/Login/LoginForm/useStyles.ts
> +    color: 'rgb(0,0,0)',
This was part of the default styling but I have changed it to `color="textPrimary"` on the latest commit.

2021-10-21 17:23 UTC, navjot-chahal commented on client/src/pages/SignUp/useStyles.ts
> +    fontFamily: theme.typography.fontFamily,
Reverted back!

2021-10-21 17:28 UTC, navjot-chahal commented
@ugur-akin Please review the changes in `Hotfix -1`. Thanks for your detailed comments on my PR. 😄

2021-10-22 00:01 UTC, rajivtitus commented on client/src/pages/Login/LoginForm/useStyles.ts
> +    textTransform: 'uppercase',
👍🏽

2021-10-22 00:05 UTC, rajivtitus commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +            <Typography className={classes.boldText}> Don&apos;t have account? </Typography>
```suggestion
            <Typography className={classes.boldText}> {"Don't have account? "} </Typography>
```
I think using a string is much simpler than using HTML entities 😄

2021-10-22 00:08 UTC, rajivtitus commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +            <Typography className={classes.boldText}> Don&apos;t have account? </Typography>
```suggestion
            <Typography className={classes.boldText}> {"Don't have account? "}</Typography>
```

I think a lot simpler to use the Unicode character within a string instead of HTML entities 😄

2021-10-22 00:09 UTC, rajivtitus approved these changes
UI looks great! Good work making those requested changes 👍🏽

2021-10-22 01:20 UTC, navjot-chahal commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +            <Typography className={classes.boldText}> Don&apos;t have account? </Typography>
Haha! True, I will add that! 😀

![image](https://user-images.githubusercontent.com/60498899/138378030-81168be1-fef4-498b-929f-97f3cc5abe6e.png)

2021-10-22 14:18 UTC, merged

2021-10-22 20:28 UTC, rajivtitus commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +            <Typography className={classes.boldText}> Don&apos;t have account? </Typography>
This is hilarious 🤣