FE/IN: Feature profile details page
hatchways/team-scallops pull request #72
Opened 2021-10-23 06:20 UTC by MarianaES

### What this PR does (required):
- Implement UI for the Profile Details Page of the sitters.
- Add integration to the page which means that user can send a request with a specific date and time for drop in and drop off their pets. 

### Screenshots / Videos (front-end only):

https://user-images.githubusercontent.com/29843870/139189612-e40c6676-64f4-4bd4-93c9-2bcb9f31c62b.mov

![image](https://user-images.githubusercontent.com/29843870/138545025-85e459eb-5e01-4115-8afb-5c98fc558531.png)

### Any information needed to test this feature (required):
- You will need to run `npm ci` to update `@material-ui/core`.

2021-10-25 15:19 UTC, ugur-akin requested changes
Looks great overall, good job! ❤️  I left a few comments for you to address, let's check back once you are able to have a look 👍🏼 

I really like how the UI looks! One thing I noticed though was that the profile card didn't have rounded edges unlike the mocks. Is that something we can address?

Thanks for all your work 🙏🏼

2021-10-25 15:19 UTC, ugur-akin commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +import Typography from '@material-ui/core/Typography';
You can group these imports for brevity (e.g. `import {Card, Button, Box} from '@material-ui/core'}`) 👍🏼

2021-10-25 15:19 UTC, ugur-akin commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +import person from '../../Images/d9fc84a0d1d545d77e78aaad39c20c11d3355074.png';
Good job leveraging [CRA](https://create-react-app.dev/)'s bundling to import images! I would recommend naming/pathing each image properly for clarity (e.g. `profileDetailsDog.jpeg` or `images/ProfileDetails/dog.jpeg`). I think the `images` folder should be lowercase to better align with the project's hierarchy 👍🏼

2021-10-25 15:19 UTC, ugur-akin commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +            <Card className={classes.profileDetail}>
This looks good but I think there is a bit of a problem with the component hierarchy here. Looks to me like the whole details component could be a `Card` (i.e. no need for `Paper` separately). Cover looks good but it has an inaccurate title :)

2021-10-25 15:19 UTC, ugur-akin commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +                </Typography>
Love these! My only advice would be to avoid hard coding profile details such as image paths, names, description, etc. and use a `mockProfile` dynamically render all that information! That way, most of the work will be done when it's time to integrate this page 💯 🎉

2021-10-25 15:19 UTC, ugur-akin commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +                    onChange={(date) => handleDateChange(date)}
```suggestion
                    onChange={handleDateChange}
```
You can simplify this 🙌🏼 (we should apply to all occurances 👍🏼 )

2021-10-25 15:19 UTC, ugur-akin commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +  };
There is no reason to return `date` here ([the api doesn't expect a return value](https://material-ui-pickers.dev/api/DatePicker)). We can in fact get rid of this method, and just provide `setSelectedDate` to `onChange` events. Also, we should have 2 states, one each for drop off and pick up 👍🏼

2021-10-25 15:19 UTC, ugur-akin commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +                    onChange={(date) => handleDateChange(date)}
The values of these two should be different than the above two (drop off vs. pick up)

2021-10-25 15:19 UTC, ugur-akin commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +                  send request
Nice touch with `textTrasnform` here ❤️

2021-10-25 15:19 UTC, ugur-akin commented on client/src/pages/ProfileDetails/useStyles.tsx
> +    backgroundColor: '#ff4545',
You already have a `color` prop set on the button, do we need this as well?

2021-10-25 15:19 UTC, ugur-akin commented on client/src/pages/ProfileDetails/useStyles.tsx
> +    paddingLeft: theme.spacing(8),
These paddings are perfectly fine, however, it can become difficult to maintain a consistent look throughout the app if we apply spacing too generously. Try to apply these only if necessary 👍🏼

2021-10-25 15:19 UTC, ugur-akin commented on client/src/App.tsx
> +                <Route path="/sitter/detail" component={ProfileDetails} />
I think it would be a good idea to make `profile` route `exact` and re-route this to `/profile/details`. When we integrate, we can then append an `/:id` slug to differentiate which profile's details we want to fetch 👍🏼

2021-10-25 15:19 UTC, ugur-akin commented on client/src/pages/Dashboard/Dashboard.tsx
> +      <Link to="/sitter/detail"> Sitter Profile Detail</Link>
It's best to either: 
- not include this in the PR, or,
- leaving a comment to indicate this is a temporary change (e.g. `TODO(Mariana): This should be removed when the component is integrated`). 

I tend to prefer the latter 👍🏼

2021-10-26 18:37 UTC, rajivtitus commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +                <ImageList rowHeight={160} cols={4}>
👍🏽

2021-10-26 18:38 UTC, rajivtitus commented on client/src/pages/ProfileDetails/useStyles.tsx
> +    textTransform: 'uppercase',
💯

2021-10-26 18:41 UTC, rajivtitus commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +  const [selectedDate, setSelectedDate] = useState<MaterialUiPickersDate>(new Date());
As per Ugur's comment we will need separate states for 'drop off' and 'drop in' dates or you can consider using a single state which consists of a date range.

Eg: ` const [dateRange, setDateRange] = useState<DateRange<Date | null>>([null, null]);`

2021-10-26 18:43 UTC, rajivtitus reviewed
Great usage of MUI and I also love the UI 🚀 

Please have a look at the comments and address them :)

2021-10-27 02:37 UTC, MarianaES commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +                </Typography>
If I am doing the integration (getting some fields already) but some values are still pending to be include in the profile model, is it better to keep using a mockProfile or adding notes such as `{/* TODO: Add rate to the Profile Model, adjust to profile.rate. */}` within the file?

2021-10-27 04:51 UTC, MarianaES commented on client/src/pages/ProfileDetails/useStyles.tsx
> +    backgroundColor: '#ff4545',
The color prop is to set colorText to white and backgroundColor is to set a color similar to the mock.

2021-10-27 04:56 UTC, MarianaES commented on client/src/pages/ProfileDetails/useStyles.tsx
> +    paddingLeft: theme.spacing(8),
Ok, thanks.  Is the use of the theme.spacing() a good practice? under which circumstances?

2021-10-27 10:42 UTC, ugur-akin commented on client/src/pages/ProfileDetails/useStyles.tsx
> +    backgroundColor: '#ff4545',
I see. This is fine for now but later, can we instead modify the theme color palette for this? `#ff4545` should really be our primary color as it's used throughout the whole app (it's set to a shade of blue at the moment). Also, [here](https://v4.mui.com/customization/palette/#customization) you can find more info on how to customize the theme palette 👍🏼

2021-10-27 10:44 UTC, ugur-akin commented on client/src/pages/ProfileDetails/useStyles.tsx
> +    paddingLeft: theme.spacing(8),
`theme.spacing()` should always be the preferred way when setting margins/paddings for consistency reasons. However, we should try to avoid adding margins/paddings to arbitrary components unless necessary 👍🏼

2021-10-27 10:54 UTC, ugur-akin commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +                </Typography>
I prefer using a mock still when this is the case, but leaving a comment is a very good alternative too!

Wearing my technicality hat to go into a bit more detail here 🎩 :
Technically, the objects you use on the frontend aren't tightly coupled to the objects you store in the database, instead they are connected through the API layer (where you fetch stuff from your backend). You can always implement more logic there to transform the objects you get from your backend (e.g. fetch both the rating and profile from different endpoints and combine them into a single object).

2021-10-27 22:37 UTC, MarianaES commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +                </Typography>
Thanks, makes sense!

2021-10-28 15:06 UTC, ugur-akin reviewed
Thanks for your diligent work! This looks almost complete, great job! 🎉 Nice use of formik too... Just noted a few minor issues, we should be able to merge when they are fixed and all the merge conflicts are resolved.

The request model will usually expect `Date` values for start/end dates. Providing a formatted date string should work fine, but I'd recommend testing it to double-check (if it works then you can ignore my comment about returning a `Date` object).

2021-10-28 15:06 UTC, ugur-akin commented on client/src/pages/SitterDetails/SitterDetails.tsx
> +  }, []);
We can remove this line and pass the `getSitterDetails` function as a dependency to the `useEffect` hook.

Or better, you can move its definition inside the `useEffect` hook 👍🏼

2021-10-28 15:06 UTC, ugur-akin commented on client/src/pages/SitterDetails/SitterDetails.tsx
> +    { setSubmitting }: FormikHelpers<{ dropInDate: Date; dropInTime: Date; dropOffDate: Date; dropOffTime: Date }>,
Optionally, you can refactor this into an interface to improve readability here.

2021-10-28 15:06 UTC, ugur-akin commented on client/src/pages/SitterDetails/SitterDetails.tsx
> +    return dateAndTime;
It might be better to return a `Date` object here instead of a string (based on what the request model expects). You can achieve this with with the `Date()` constructor or `Date.parse()` 👍🏼

2021-10-28 15:06 UTC, ugur-akin commented on server/controllers/profile.js
> +  console.log({ profile });
Let's remove these console statements 👍🏼

2021-10-28 15:06 UTC, ugur-akin commented on server/controllers/profile.js
> +    profile = await Profile.findOne({ _id: sitterId });
Alternatively, we can use `findById` query 👍🏼

2021-10-29 09:58 UTC, ugur-akin approved these changes
LGTM! ❤️ 

Small note: TS Interface names are usually defined in `PascalCase` so let's use that in the future and try to fix `camelCase` ones as we go along 👍🏼

2021-10-30 21:56 UTC, merged