Feature profile listings #21
hatchways/team-scallops pull request #75
Opened 2021-10-24 07:22 UTC by DestinTech

### What this PR does (required):
Create a page to list all the profiles

### Screenshots / Videos (front-end only):
<img width="880" alt="Screen Shot 2021-10-29 at 6 40 25 AM" src="https://user-images.githubusercontent.com/4998567/139436228-a967b11b-f6f2-49ec-b2cf-c0f531d6a10f.png">

### Any information needed to test this feature (required):
Go to dashboard, click search page
### Any issues with the current functionality (optional):
- Integration is separate ticket
- Styling could be better

2021-10-24 11:58 UTC, sundayezeilo commented
Please resolve merge conflict

2021-10-24 12:05 UTC, sundayezeilo requested changes
Looks good! Please resolve the merge conflict on this PR before it can be approved. Also, remember to always link your ticket in all your future PRs.

2021-10-24 12:05 UTC, sundayezeilo commented on client/src/pages/Profile/ProfileEdit/ProfileEditForm/ProfileEditForm.tsx
> +                  axios.patch('/profile/', modifiedValues);
Correct use of HTTP verb :+1:

2021-10-24 12:05 UTC, sundayezeilo requested changes
Looks good! Please resolve the merge conflict on this PR before it can be approved.

2021-10-28 09:08 UTC, rajivtitus commented on client/src/components/DateRangePicker/DatePicker.tsx
> +export default function DatePicker(props: any): JSX.Element {
Please avoid using 'any' as a type

Ditto throughout!

2021-10-28 09:10 UTC, rajivtitus commented on client/src/pages/ProfileList/List.tsx
> +    return <Box>loading</Box>;
You can use the MUI 'CircularProgress' component here :)

2021-10-28 09:10 UTC, rajivtitus commented on client/src/pages/ProfileList/List.tsx
> +              ${moment(selection.startDate).format('DD-')}${`${moment(selection.endDate).format('DD MMMM YYYY')}`}
👍🏽

2021-10-28 09:11 UTC, rajivtitus commented on client/src/pages/ProfileList/List.tsx
> +                          <Typography> Rating</Typography>
You can use the MUI Rating component here (make sure its ReadOnly)

2021-10-28 09:12 UTC, rajivtitus commented on client/src/pages/ProfileList/List.tsx
> +                          <Typography>{/* <Link to={`profile?user=${userId}`}> {userId}</Link>*/}</Typography>
You can use the card action area 😉 

```
<Card>
  <CardActionArea component={Link} to=".....">
    <CardContent>
      ............
     </CardContent>
  </CardActionArea>
</Card>
```

2021-10-28 09:13 UTC, rajivtitus commented on client/src/pages/ProfileList/List.tsx
> +                        <Typography className={classes.price}>$20/hr</Typography>
Note: In the future, consider storing these values in an object (makes the integration a lot simpler to implement) as opposed to hardcoding them :)

2021-10-28 09:15 UTC, rajivtitus commented on client/src/pages/ProfileList/List.tsx
> +                  <Card style={{ height: '100%' }} variant="outlined" key={key}>
It would be nice if you could componentize the ListingsCard 😄

2021-10-28 09:16 UTC, rajivtitus commented on client/src/pages/ProfileList/List.tsx
> +  const [state, setState] = useState({
```suggestion
  const [state, setState] = useState<Profile[]>([])
```

We can use the Profile interface if we have one. Also, using an array will avoid the need for the variable on line 39

2021-10-28 09:17 UTC, rajivtitus reviewed
UI looks good! Nice work here, just a few comments for you to address. Thanks :)

2021-10-29 10:22 UTC, dTechLife commented on client/src/pages/ProfileList/List.tsx
> +                        <Typography className={classes.price}>$20/hr</Typography>
Definitely Next time I'll hard code them into an object at the top of the file. 

should add a TODO:  I'd like to grab those details from a new route that serves profile details but is restricted to the approximate location, price, etc.

2021-10-29 10:23 UTC, dTechLife commented on client/src/components/DateRangePicker/DatePicker.tsx
> +export default function DatePicker(props: any): JSX.Element {
Using any defeats the purpose of typescript. Noted!

2021-10-31 20:05 UTC, rajivtitus commented on client/src/pages/ProfileList/List.tsx
> +                <Grid item key={key}>
Using indexes as keys in React is considered an anti-pattern and not recommend. Please consider using a unique identifier as a key :)

Ref: https://medium.com/wesionary-team/using-index-as-a-key-is-an-anti-pattern-in-react-8e5db3aea3a9

2021-10-31 20:07 UTC, rajivtitus approved these changes
@DestinTech Thanks for making the requested changes, please address the comment about 'usage of indexes as keys in React' prior to merging. The TS 'any' comments are optional for now but please make sure you use appropriate types in any future PRs.

2021-11-01 22:28 UTC, rajivtitus commented
PR was accidentally closed!

2021-11-02 00:49 UTC, merged