Feature stripe api #40
hatchways/team-scallops pull request #81
Opened 2021-10-26 03:09 UTC by DestinTech

### What this PR does (required):
Added stripe API requirements
please check slack for API Keys. 

### Any information needed to test this feature (required):
Further integration is required to test. 

### Any issues with the current functionality (optional):
Unsure if I should make routes for API or if that's a separate ticket

2021-10-26 03:11 UTC, dTechLife commented
* Note, bugfix for cookies not included after discussing with team. Hotfix created.

2021-10-27 11:41 UTC, jerixmx reviewed
Hi! Yes, please use this PR to set up the user for payments. You can focus on the backend. This will involve:
1. Creating the **customer account** for the user and **SetupIntent** in Stripe
2. Adding payment methods for the customer
3. Retrieving the list of a customer's payment methods

This is probably the closest workflow for the Dog Sitter app: [Set up future payments](https://stripe.com/docs/payments/save-and-reuse?platform=web)

Please also update your `sample.env` files to reflect the variables you're using for the Stripe keys.

2021-10-27 11:41 UTC, jerixmx commented on server/app.js
> +const { env } = require("process");
dotenv is already set up in `server/bin/www` so we can remove this

2021-10-27 11:41 UTC, jerixmx commented on server/app.js
> +const stripe = require("stripe")(process.env.STRIPE_SECRET);
This would instead live in the payments controller

2021-10-27 15:00 UTC, dTechLife commented on server/app.js
> +const stripe = require("stripe")(process.env.STRIPE_SECRET);
Thanks for clarifying all this, I wasn't sure how far to take the integration!

2021-10-29 16:49 UTC, jerixmx requested changes
Hey Destin, I hope you had fun going through Stripe API docs! Great progress here :+1: I left some comments and suggestions. With those addressed, you should be able to make successful API calls for customer creation and client secret.

If your app supports multiple payment methods, you may have to make a **route for listing the customer's payment methods**. 

Another tip (optional): Right now, when getting the client secret, a setupIntent is created. It's possible that the customer already has a setupIntent created, but it's not yet fulfilled (it doesn't have a payment method successfully linked yet). It would be better to **check first whether a customer has an existing unfulfilled setupIntent** instead of making one each time the secret is retrieved. [ref](https://stripe.com/docs/api/setup_intents/object#setup_intent_object-status)

2021-10-29 16:49 UTC, jerixmx commented on server/controllers/payments.js
> +    customer: req.user.id,
The value here should be the customer ID from Stripe, not the user ID from the request :)

2021-10-29 16:49 UTC, jerixmx commented on server/routes/payment.js
> +const { validateRegister, validateLogin } = require("../validate");
You may have missed removing this line :)

2021-10-29 16:49 UTC, jerixmx commented on server/routes/auth.js
> +router.route("/logout").post(logoutUser);
:+1:

2021-10-29 16:49 UTC, jerixmx commented on server/controllers/profile.js
> -    i;
:+1:

2021-10-29 16:49 UTC, jerixmx commented on server/controllers/payments.js
> +    id: req.user.id,
No need to supply. Stripe customer creation API doesn't have ID in its parameters.

2021-10-29 16:49 UTC, jerixmx commented on server/controllers/payments.js
> +exports.stripeSetup = asyncHandler(async (req, res) => {
Since this is triggered by user registration (instead of an API call), it may be better to make this a regular function (no need for req, res) that accepts email as a parameter and returns the Stripe customer ID.

2021-10-29 16:49 UTC, jerixmx commented on server/controllers/payments.js
> +    email: req.user.email,
Good initiative including the email in Stripe customer creation! Email is not part of the token (where `req.user` is from) though, and `req.user` is not accessible here. You could get the email as a parameter when `stripeSetup` is called instead.

2021-10-29 16:49 UTC, jerixmx commented on server/controllers/auth.js
> +    await stripeSetup();
Let's store the Stripe customer ID for reference so we can use it when we need to create setupIntents, retrieve payment methods, and charge the customer. You can add it in the User model.

2021-10-31 21:01 UTC, rajivtitus commented
@DestinTech no new comments from me, please address Jeri's comments :)

2021-11-02 20:31 UTC, DestinTech commented on server/controllers/auth.js
> +    await stripeSetup();
Should I be storing the setupIntent client secret, or setupIntent ID as well in the User model? Without doing that the setupIntent client secret is different on every call. Thanks for the help!

2021-11-04 16:01 UTC, jerixmx commented on server/controllers/auth.js
> +    await stripeSetup();
Hey Destin, sorry for the late revert, had a problem with our network for a couple of days :pensive: 

The client secret shouldn't be stored, but I'm not seeing any issue with storing the setupIntentID. One thing to note is that after the payment method has been added (ie setupIntent has been fulfilled), I don't think we'd still need the setupIntent ID. An alternative (optional) would be to make a Stripe API call that lists the customer's existing setupIntents ([ref](https://stripe.com/docs/api/setup_intents/list)). One advantage of this is that its returned object already includes the status and client secret of the setupIntent.

Please refer to my previous [tip](https://github.com/hatchways/team-scallops/pull/81#pullrequestreview-793129905) for your dilemma re new secret/setupIntent each call :)

2021-11-04 16:26 UTC, jerixmx requested changes
Thank you for resolving my previous comments! 

You just need to clean out/remove the console logs and correct a typo. I also gave some [suggestions](https://github.com/hatchways/team-scallops/pull/81#discussion_r742982818) but these are optional.

I hope you and your team have fun setting up your payments system with this!

2021-11-04 16:26 UTC, jerixmx commented on server/controllers/payments.js
> +    customer: user.StripeCustomerId,
Got a typo here :)
```suggestion
    customer: user.stripeCustomerId,
```

2021-11-05 07:56 UTC, DestinTech commented on server/controllers/auth.js
> +    await stripeSetup();
Thanks for all your help with stripe, its use case is amazing once you wrap you head around it. I was moving last week as well so sorry if any comments were missed, I read them but sometimes forget to reply and just implement what was said 🥇 Thanks again for your help!

2021-11-05 10:25 UTC, jerixmx requested changes
Hi Destin, you may have missed these console logs:

2021-11-05 10:25 UTC, jerixmx commented on server/controllers/auth.js
> +  console.log(stripeCustomerId);
Please remove

2021-11-05 10:25 UTC, jerixmx commented on server/controllers/auth.js
> +  console.log(user);
Please remove

2021-11-05 10:30 UTC, DestinTech commented on server/controllers/auth.js
> +  console.log(stripeCustomerId);
whoops, thanks! Late night!

2021-11-05 10:39 UTC, jerixmx approved these changes
Approved :+1: ! Please resolve conflicts before merging!

2021-11-05 10:52 UTC, merged